services:

  db:
    image: postgres:15
    container_name: bank-db
    environment:
      POSTGRES_DB: bank
      POSTGRES_USER: mon
      POSTGRES_PASSWORD: MoNeY
    ports:
      - "5433:5432"

  backend:
    build: ./backend
    ports:
      - "8081:8081"
    volumes:
      - ./backend:/app
      - maven-cache:/root/.m2
    depends_on:
      - db
    environment:
      SPRING_DEVTOOLS_RESTART_ENABLED: "true"

  frontend:
    build: ./frontend
    ports:
       - "5174:5174"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  maven-cache:

